PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE movies(movie_id integer primary key not null, title text);
INSERT INTO "movies" VALUES(1,'Apornas planet');
INSERT INTO "movies" VALUES(2,'Top Gun');
INSERT INTO "movies" VALUES(3,'Mission impossible');
INSERT INTO "movies" VALUES(4,'Deerhunter');
INSERT INTO "movies" VALUES(5,'Taxidriver');
INSERT INTO "movies" VALUES(6,'Rocky');
CREATE TABLE actors(actor_id integer primary key not null, name);
INSERT INTO "actors" VALUES(1,'Charlton Heston');
INSERT INTO "actors" VALUES(2,'Tom Cruise');
INSERT INTO "actors" VALUES(3,'Robert De Niro');
INSERT INTO "actors" VALUES(4,'Sylvester Stallone');
INSERT INTO "actors" VALUES(5,'Meryl Streep');
CREATE TABLE reviews(review_id integer primary key not null, movie_id integer, review text);
CREATE TABLE actors_movies(actor_id integer, movie_id integer);
INSERT INTO "actors_movies" VALUES(1,1);
INSERT INTO "actors_movies" VALUES(2,2);
INSERT INTO "actors_movies" VALUES(2,3);
INSERT INTO "actors_movies" VALUES(3,4);
INSERT INTO "actors_movies" VALUES(3,5);
INSERT INTO "actors_movies" VALUES(4,6);
INSERT INTO "actors_movies" VALUES(5,4);
COMMIT;
