PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS "municipalities";
DROP TABLE IF EXISTS "municipality_id_www_only";
CREATE TABLE "municipalities"(MunicipalityID INTEGER PRIMARY KEY NOT NULL,Name text, URL text, HTTPS boolean,Server text);
INSERT INTO "municipalities" VALUES(1,'Ale kommun','http://www.ale.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(2,'Alingsås kommun','http://www.alingsas.se/',1,'Apache/2.2.29 (FreeBSD) PHP/5.3.29 with Suhosin-Patch mod_ssl/2.2.29 OpenSSL/0.9.8zd-freebsd DAV/2');
INSERT INTO "municipalities" VALUES(3,'Alvesta kommun','http://www.alvesta.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(4,'Aneby kommun','http://www.aneby.se/',0,'Apache/2.2.22 (Ubuntu)');
INSERT INTO "municipalities" VALUES(5,'Arboga kommun','http://www.arboga.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(6,'Arjeplogs kommun','http://www.arjeplog.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(7,'Arvidsjaurs kommun','http://www.arvidsjaur.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(8,'Arvika kommun','http://www.arvika.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(9,'Askersunds kommun','http://www.askersund.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(10,'Avesta kommun','http://www.avesta.se/',0,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(11,'Bengtsfors kommun','http://www.bengtsfors.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(12,'Bergs kommun','http://www.berg.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(13,'Bjurholms kommun','http://www.bjurholm.se/',0,NULL);
INSERT INTO "municipalities" VALUES(14,'Bjuvs kommun','http://www.bjuv.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(15,'Bodens kommun','http://www.boden.se/',0,NULL);
INSERT INTO "municipalities" VALUES(16,'Bollebygds kommun','http://www.bollebygd.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(17,'Bollnäs kommun','http://www.bollnas.se/',0,NULL);
INSERT INTO "municipalities" VALUES(18,'Borgholms kommun','http://www.borgholm.se/',0,'Apache/2.2.22 (Ubuntu)');
INSERT INTO "municipalities" VALUES(19,'Borlänge kommun','http://www.borlange.se/',1,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(20,'Borås stad','http://www.boras.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(21,'Botkyrka kommun','http://www.botkyrka.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(22,'Boxholms kommun','http://www.boxholm.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(23,'Bromölla kommun','http://www.bromolla.se/',0,'Microsoft-IIS/7.0');
INSERT INTO "municipalities" VALUES(24,'Bräcke kommun','http://www.bracke.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(25,'Burlövs kommun','http://www.burlov.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(26,'Båstads kommun','http://www.bastad.se/',0,'Microsoft-IIS/7.0');
INSERT INTO "municipalities" VALUES(27,'Dals-Eds kommun','http://www.dalsed.se/',0,NULL);
INSERT INTO "municipalities" VALUES(28,'Danderyds kommun','http://www.danderyd.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(29,'Degerfors kommun','http://www.degerfors.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(30,'Dorotea kommun','http://www.dorotea.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(31,'Eda kommun','http://www.eda.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(32,'Ekerö kommun','http://www.ekero.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(33,'Eksjö kommun','http://www.eksjo.se/',0,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(34,'Emmaboda kommun','http://www.emmaboda.se/',0,'Microsoft-IIS/6.0');
INSERT INTO "municipalities" VALUES(35,'Enköpings kommun','http://www.enkoping.se/',0,'Apache');
INSERT INTO "municipalities" VALUES(36,'Eskilstuna kommun','http://eskilstuna.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(37,'Eslövs kommun','http://www.eslov.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(38,'Essunga kommun','http://www.essunga.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(39,'Fagersta kommun','http://www.fagersta.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(40,'Falkenbergs kommun','http://www.falkenberg.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(41,'Falköpings kommun','http://www.falkoping.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(42,'Falu kommun','http://www.falun.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(43,'Filipstads kommun','http://www.filipstad.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(44,'Finspångs kommun','http://www.finspang.se/',1,'Microsoft-IIS/6.0');
INSERT INTO "municipalities" VALUES(45,'Flens kommun','http://www.flen.se/',0,NULL);
INSERT INTO "municipalities" VALUES(46,'Forshaga kommun','http://www.forshaga.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(47,'Färgelanda kommun','http://www.fargelanda.se/',0,NULL);
INSERT INTO "municipalities" VALUES(48,'Gagnefs kommun','http://www.gagnef.se/',0,NULL);
INSERT INTO "municipalities" VALUES(49,'Gislaveds kommun','http://www.gislaved.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(50,'Gnesta kommun','http://www.gnesta.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(51,'Gnosjö kommun','http://www.gnosjo.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(52,'Region Gotland','http://www.gotland.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(53,'Grums kommun','http://www.grums.se/',0,'Unknown');
INSERT INTO "municipalities" VALUES(54,'Grästorps kommun','http://www.grastorp.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(55,'Gullspångs kommun','http://www.gullspang.se/',0,NULL);
INSERT INTO "municipalities" VALUES(56,'Gällivare kommun','http://www.gellivare.se/',0,'Microsoft-HTTPAPI/2.0');
INSERT INTO "municipalities" VALUES(57,'Gävle kommun','http://www.gavle.se/',1,NULL);
INSERT INTO "municipalities" VALUES(58,'Göteborgs stad','http://www.goteborg.se/',1,NULL);
INSERT INTO "municipalities" VALUES(59,'Götene kommun','http://www.gotene.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(60,'Habo kommun','http://www.habokommun.se/',0,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(61,'Hagfors kommun','http://www.hagfors.se/',0,'Apache/2.2.22 (Ubuntu)');
INSERT INTO "municipalities" VALUES(62,'Hallsbergs kommun','http://www.hallsberg.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(63,'Hallstahammars kommun','http://www.hallstahammar.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(64,'Halmstads kommun','http://www.halmstad.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(65,'Hammarö kommun','http://www.hammaro.se/',1,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(66,'Haninge kommun','http://www.haninge.se/',0,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(67,'Haparanda stad','http://www.haparanda.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(68,'Heby kommun','http://www.heby.se/',1,'Apache');
INSERT INTO "municipalities" VALUES(69,'Hedemora kommun','http://www.hedemora.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(70,'Helsingborgs stad','http://www.helsingborg.se/',0,'nginx/1.6.2');
INSERT INTO "municipalities" VALUES(71,'Herrljunga kommun','http://www.herrljunga.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(72,'Hjo kommun','http://www.hjo.se/',0,NULL);
INSERT INTO "municipalities" VALUES(73,'Hofors kommun','http://www.hofors.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(74,'Huddinge kommun','http://www.huddinge.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(75,'Hudiksvalls kommun','http://www.hudiksvall.se/',0,NULL);
INSERT INTO "municipalities" VALUES(76,'Hultsfreds kommun','http://www.hultsfred.se/',0,'Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.13 OpenSSL/1.0.1f');
INSERT INTO "municipalities" VALUES(77,'Hylte kommun','http://www.hylte.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(78,'Håbo kommun','http://www.habo.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(79,'Hällefors kommun','http://www.hellefors.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(80,'Härjedalens kommun','http://www.herjedalen.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(81,'Härnösands kommun','http://www.harnosand.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(82,'Härryda kommun','http://www.harryda.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(83,'Hässleholms kommun','http://www.hassleholm.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(84,'Höganäs kommun','http://www.hoganas.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(85,'Högsby kommun','http://www.hogsby.se/',0,'Apache/2.2.16 (Ubuntu)');
INSERT INTO "municipalities" VALUES(86,'Hörby kommun','http://www.horby.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(87,'Höörs kommun','http://www.hoor.se/',0,'Microsoft-IIS/6.0');
INSERT INTO "municipalities" VALUES(88,'Jokkmokks kommun','http://www.jokkmokk.se/',0,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(89,'Järfälla kommun','http://www.jarfalla.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(90,'Jönköpings kommun','http://www.jonkoping.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(91,'Kalix kommun','http://www.kalix.se/',0,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(92,'Kalmar kommun','http://www.kalmar.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(93,'Karlsborgs kommun','http://www.karlsborg.se/',0,NULL);
INSERT INTO "municipalities" VALUES(94,'Karlshamns kommun','http://www.karlshamn.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(95,'Karlskoga kommun','http://www.karlskoga.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(96,'Karlskrona kommun','http://www.karlskrona.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(97,'Karlstads kommun','http://www.karlstad.se/',0,NULL);
INSERT INTO "municipalities" VALUES(98,'Katrineholms kommun','http://www.katrineholm.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(99,'Kils kommun','http://www.kil.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(100,'Kinda kommun','http://www.kinda.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(101,'Kiruna kommun','http://www.kiruna.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(102,'Klippans kommun','http://www.klippan.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(103,'Knivsta kommun','http://www.knivsta.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(104,'Kramfors kommun','http://www.kramfors.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(105,'Kristianstads kommun','http://www.kristianstad.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(106,'Kristinehamns kommun','http://www.kristinehamn.se/',0,'Apache/2.2.10 (Linux/SUSE)');
INSERT INTO "municipalities" VALUES(107,'Krokoms kommun','http://www.krokom.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(108,'Kumla kommun','http://www.kumla.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(109,'Kungsbacka kommun','http://www.kungsbacka.se/',1,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(110,'Kungsörs kommun','http://www.kungsor.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(111,'Kungälvs kommun','http://www.kungalv.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(112,'Kävlinge kommun','http://www.kavlinge.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(113,'Köpings kommun','http://www.koping.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(114,'Laholms kommun','http://www.laholm.se/',0,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(115,'Landskrona stad','http://www.landskrona.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(116,'Laxå kommun','http://www.laxa.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(117,'Lekebergs kommun','http://www.lekeberg.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(118,'Leksands kommun','http://www.leksand.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(119,'Lerums kommun','http://www.lerum.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(120,'Lessebo kommun','http://www.lessebo.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(121,'Lidingö stad','http://www.lidingo.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(122,'Lidköpings kommun','http://www.lidkoping.se/',1,'nginx');
INSERT INTO "municipalities" VALUES(123,'Lilla Edets kommun','http://www.lillaedet.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(124,'Lindesbergs kommun','http://www.lindesberg.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(125,'Linköpings kommun','http://www.linkoping.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(126,'Ljungby kommun','http://www.ljungby.se/',0,'Microsoft-IIS/6.0');
INSERT INTO "municipalities" VALUES(127,'Ljusdals kommun','http://www.ljusdal.se/',0,NULL);
INSERT INTO "municipalities" VALUES(128,'Ljusnarsbergs kommun','http://www.ljusnarsberg.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(129,'Lomma kommun','http://www.lomma.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(130,'Ludvika kommun','http://www.ludvika.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(131,'Luleå kommun','http://www.lulea.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(132,'Lunds kommun','http://www.lund.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(133,'Lycksele kommun','http://www.lycksele.se/',0,'Microsoft-IIS/6.0');
INSERT INTO "municipalities" VALUES(134,'Lysekils kommun','http://www.lysekil.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(135,'Malmö stad','http://www.malmo.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(136,'Malung-Sälens kommun','http://www.malung-salen.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(137,'Malå kommun','http://www.mala.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(138,'Mariestads kommun','http://www.mariestad.se/',0,NULL);
INSERT INTO "municipalities" VALUES(139,'Markaryds kommun','http://www.markaryd.se/',0,'Apache/2.2.8 (Ubuntu) PHP/5.2.4-2ubuntu5.23 with Suhosin-Patch mod_ssl/2.2.8 OpenSSL/0.9.8g');
INSERT INTO "municipalities" VALUES(140,'Marks kommun','http://www.mark.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(141,'Melleruds kommun','http://www.mellerud.se/',0,NULL);
INSERT INTO "municipalities" VALUES(142,'Mjölby kommun','http://www.mjolby.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(143,'Mora kommun','http://www.mora.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(144,'Motala kommun','http://www.motala.se/',0,'Apache/2.2.22');
INSERT INTO "municipalities" VALUES(145,'Mullsjö kommun','http://www.mullsjo.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(146,'Munkedals kommun','http://www.munkedal.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(147,'Munkfors kommun','http://www.munkfors.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(148,'Mölndals stad','http://www.molndal.se/',1,'nginx');
INSERT INTO "municipalities" VALUES(149,'Mönsterås kommun','http://www.monsteras.se/',0,'Apache');
INSERT INTO "municipalities" VALUES(150,'Mörbylånga kommun','http://www.morbylanga.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(151,'Nacka kommun','http://www.nacka.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(152,'Nora kommun','http://www.nora.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(153,'Norbergs kommun','http://www.norberg.se/',0,NULL);
INSERT INTO "municipalities" VALUES(154,'Nordanstigs kommun','http://www.nordanstig.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(155,'Nordmalings kommun','http://www.nordmaling.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(156,'Norrköpings kommun','http://www.norrkoping.se/',0,'Roxen/5.4.74-r1');
INSERT INTO "municipalities" VALUES(157,'Norrtälje kommun','http://www.norrtalje.se/',1,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(158,'Norsjö kommun','http://www.norsjo.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(159,'Nybro kommun','http://www.nybro.se/',0,'Apache');
INSERT INTO "municipalities" VALUES(160,'Nykvarns kommun','http://www.nykvarn.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(161,'Nyköpings kommun','http://www.nykoping.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(162,'Nynäshamns kommun','http://www.nynashamn.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(163,'Nässjö kommun','http://www.nassjo.se/',0,'Apache/2.2.22 (Win32) mod_ssl/2.2.22 OpenSSL/0.9.8t PHP/5.2.17');
INSERT INTO "municipalities" VALUES(164,'Ockelbo kommun','http://www.ockelbo.se/',0,NULL);
INSERT INTO "municipalities" VALUES(165,'Olofströms kommun','http://www.olofstrom.se/',0,'nginx + Phusion Passenger 5.0.21');
INSERT INTO "municipalities" VALUES(166,'Orsa kommun','http://www.orsa.se/',0,'Microsoft-IIS/6.0');
INSERT INTO "municipalities" VALUES(167,'Orust kommun','http://www.orust.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(168,'Osby kommun','http://www.osby.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(169,'Oskarshamns kommun','http://www.oskarshamn.se/',1,'Microsoft-IIS/6.0');
INSERT INTO "municipalities" VALUES(170,'Ovanåkers kommun','http://www.ovanaker.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(171,'Oxelösunds kommun','http://www.oxelosund.se/',0,'Apache/2.2.22 (Ubuntu)');
INSERT INTO "municipalities" VALUES(172,'Pajala kommun','http://www.pajala.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(173,'Partille kommun','http://www.partille.se/',0,'Microsoft-IIS/7.0');
INSERT INTO "municipalities" VALUES(174,'Perstorps kommun','http://www.perstorp.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(175,'Piteå kommun','http://www.pitea.se/',1,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(176,'Ragunda kommun','http://www.ragunda.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(177,'Robertsfors kommun','http://www.robertsfors.se/',0,'Apache/2.2.16 (Debian)');
INSERT INTO "municipalities" VALUES(178,'Ronneby kommun','http://www.ronneby.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(179,'Rättviks kommun','http://www.rattvik.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(180,'Sala kommun','http://www.sala.se/',1,'Microsoft-IIS/6.0');
INSERT INTO "municipalities" VALUES(181,'Salems kommun','http://www.salem.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(182,'Sandvikens kommun','http://www.sandviken.se/',0,NULL);
INSERT INTO "municipalities" VALUES(183,'Sigtuna kommun','http://www.sigtuna.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(184,'Simrishamns kommun','http://www.simrishamn.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(185,'Sjöbo kommun','http://www.sjobo.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(186,'Skara kommun','http://www.skara.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(187,'Skellefteå kommun','http://www.skelleftea.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(188,'Skinnskattebergs kommun','http://www.skinnskatteberg.se/',0,'Apache/2.2.31 (FreeBSD) PHP/5.5.30 mod_ssl/2.2.31 OpenSSL/0.9.8zd-freebsd');
INSERT INTO "municipalities" VALUES(189,'Skurups kommun','http://www.skurup.se/',0,'Apache');
INSERT INTO "municipalities" VALUES(190,'Skövde kommun','http://www.skovde.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(191,'Smedjebackens kommun','http://www.smedjebacken.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(192,'Sollefteå kommun','http://www.solleftea.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(193,'Sollentuna kommun','http://www.sollentuna.se/',1,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(194,'Solna stad','http://www.solna.se/',1,'Microsoft-IIS/7.0');
INSERT INTO "municipalities" VALUES(195,'Sorsele kommun','http://www.sorsele.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(196,'Sotenäs kommun','http://www.sotenas.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(197,'Staffanstorps kommun','http://www.staffanstorp.se/',0,'Apache/2.2.14 (Ubuntu)');
INSERT INTO "municipalities" VALUES(198,'Stenungsunds kommun','http://www.stenungsund.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(199,'Stockholms stad','http://www.stockholm.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(200,'Storfors kommun','http://www.storfors.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(201,'Storumans kommun','http://www.storuman.se/',0,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(202,'Strängnäs kommun','http://www.strangnas.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(203,'Strömstads kommun','http://www.stromstad.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(204,'Strömsunds kommun','http://www.stromsund.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(205,'Sundbybergs stad','http://www.sundbyberg.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(206,'Sundsvalls kommun','http://www.sundsvall.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(207,'Sunne kommun','http://www.sunne.se/',0,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(208,'Surahammars kommun','http://www.surahammar.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(209,'Svalövs kommun','http://www.svalov.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(210,'Svedala kommun','http://www.svedala.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(211,'Svenljunga kommun','http://www.svenljunga.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(212,'Säffle kommun','http://www.saffle.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(213,'Säters kommun','http://www.sater.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(214,'Sävsjö kommun','http://www.savsjo.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(215,'Söderhamns kommun','http://www.soderhamn.se/',0,NULL);
INSERT INTO "municipalities" VALUES(216,'Söderköpings kommun','http://www.soderkoping.se/',0,NULL);
INSERT INTO "municipalities" VALUES(217,'Södertälje kommun','http://www.sodertalje.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(218,'Sölvesborgs kommun','http://www.solvesborg.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(219,'Tanums kommun','http://www.tanum.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(220,'Tibro kommun','http://www.tibro.se/',0,'Microsoft-IIS/6.0');
INSERT INTO "municipalities" VALUES(221,'Tidaholms kommun','http://www.tidaholm.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(222,'Tierps kommun','http://www.tierp.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(223,'Timrå kommun','http://www.timra.se/',0,NULL);
INSERT INTO "municipalities" VALUES(224,'Tingsryds kommun','http://www.tingsryd.se/',0,NULL);
INSERT INTO "municipalities" VALUES(225,'Tjörns kommun','http://www.tjorn.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(226,'Tomelilla kommun','http://www.tomelilla.se/',1,'Apache/2.4.7 (Ubuntu)');
INSERT INTO "municipalities" VALUES(227,'Torsby kommun','http://www.torsby.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(228,'Torsås kommun','http://www.torsas.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(229,'Tranemo kommun','http://www.tranemo.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(230,'Tranås kommun','http://www.tranas.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(231,'Trelleborgs kommun','http://www.trelleborg.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(232,'Trollhättans stad','http://www.trollhattan.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(233,'Trosa kommun','http://www.trosa.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(234,'Tyresö kommun','http://www.tyreso.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(235,'Täby kommun','http://www.taby.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(236,'Töreboda kommun','http://www.toreboda.se/',0,NULL);
INSERT INTO "municipalities" VALUES(237,'Uddevalla kommun','http://www.uddevalla.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(238,'Ulricehamns kommun','http://www.ulricehamn.se/',1,'Apache');
INSERT INTO "municipalities" VALUES(239,'Umeå kommun','http://www.umea.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(240,'Upplands Väsby kommun','http://www.upplandsvasby.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(241,'Upplands-Bro kommun','http://www.upplands-bro.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(242,'Uppsala kommun','http://www.uppsala.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(243,'Uppvidinge kommun','http://www.uppvidinge.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(244,'Vadstena kommun','http://www.vadstena.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(245,'Vaggeryds kommun','http://www.vaggeryd.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(246,'Valdemarsviks kommun','http://www.valdemarsvik.se/',0,'Microsoft-IIS/7.0');
INSERT INTO "municipalities" VALUES(247,'Vallentuna kommun','http://www.vallentuna.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(248,'Vansbro kommun','http://www.vansbro.se/',0,'Apache');
INSERT INTO "municipalities" VALUES(249,'Vara kommun','http://www.vara.se/',0,NULL);
INSERT INTO "municipalities" VALUES(250,'Varbergs kommun','http://www.varberg.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(251,'Vaxholms stad','http://www.vaxholm.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(252,'Vellinge kommun','http://www.vellinge.se/',0,'Microsoft-IIS/7.0');
INSERT INTO "municipalities" VALUES(253,'Vetlanda kommun','http://www.vetlanda.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(254,'Vilhelmina kommun','http://www.vilhelmina.se/',0,NULL);
INSERT INTO "municipalities" VALUES(255,'Vimmerby kommun','http://www.vimmerby.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(256,'Vindelns kommun','http://www.vindeln.se/',0,'Microsoft-IIS/6.0');
INSERT INTO "municipalities" VALUES(257,'Vingåkers kommun','http://www.vingaker.se/',0,'Microsoft-IIS/6.0');
INSERT INTO "municipalities" VALUES(258,'Vårgårda kommun','http://www.vargarda.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(259,'Vänersborgs kommun','http://www.vanersborg.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(260,'Vännäs kommun','http://www.vannas.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(261,'Värmdö kommun','http://www.varmdo.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(262,'Värnamo kommun','http://www.varnamo.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(263,'Västerviks kommun','http://www.vastervik.se/',1,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(264,'Västerås stad','http://www.vasteras.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(265,'Växjö kommun','http://www.vaxjo.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(266,'Ydre kommun','http://www.ydre.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(267,'Ystads kommun','http://www.ystad.se/',1,'Microsoft-IIS/8.0');
INSERT INTO "municipalities" VALUES(268,'Åmåls kommun','http://www.amal.se/',0,NULL);
INSERT INTO "municipalities" VALUES(269,'Ånge kommun','http://www.ange.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(270,'Åre kommun','http://www.are.se/',0,'Apache/2.2.15 (Cloud Linux)');
INSERT INTO "municipalities" VALUES(271,'Årjängs kommun','http://www.arjang.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(272,'Åsele kommun','http://www.asele.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(273,'Åstorps kommun','http://www.astorp.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(274,'Åtvidabergs kommun','http://www.atvidaberg.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(275,'Älmhults kommun','http://www.almhult.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(276,'Älvdalens kommun','http://www.alvdalen.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(277,'Älvkarleby kommun','http://www.alvkarleby.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(278,'Älvsbyns kommun','http://www.alvsbyn.se/',0,'Apache');
INSERT INTO "municipalities" VALUES(279,'Ängelholms kommun','http://www.engelholm.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(280,'Öckerö kommun','http://www.ockero.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(281,'Ödeshögs kommun','http://www.odeshog.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(282,'Örebro kommun','http://www.orebro.se/',1,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(283,'Örkelljunga kommun','http://www.orkelljunga.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(284,'Örnsköldsviks kommun','http://www.ornskoldsvik.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(285,'Östersunds kommun','http://www.ostersund.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(286,'Österåkers kommun','http://www.osteraker.se/',0,'Apache-Coyote/1.1');
INSERT INTO "municipalities" VALUES(287,'Östhammars kommun','http://www.osthammar.se/',0,'Microsoft-IIS/8.5');
INSERT INTO "municipalities" VALUES(288,'Östra Göinge kommun','http://www.ostragoinge.se/',0,'Apache');
INSERT INTO "municipalities" VALUES(289,'Överkalix kommun','http://www.overkalix.se/',0,'Microsoft-IIS/7.5');
INSERT INTO "municipalities" VALUES(290,'Övertorneå kommun','http://www.overtornea.se/',0,'Microsoft-IIS/7.5');
CREATE TABLE municipality_id_www_only(MunicipalityID INTEGER PRIMARY KEY NOT NULL, AllowsOnlyWWW boolean);
INSERT INTO "municipality_id_www_only" VALUES(1,0);
INSERT INTO "municipality_id_www_only" VALUES(2,0);
INSERT INTO "municipality_id_www_only" VALUES(3,0);
INSERT INTO "municipality_id_www_only" VALUES(4,0);
INSERT INTO "municipality_id_www_only" VALUES(5,0);
INSERT INTO "municipality_id_www_only" VALUES(6,0);
INSERT INTO "municipality_id_www_only" VALUES(7,0);
INSERT INTO "municipality_id_www_only" VALUES(8,0);
INSERT INTO "municipality_id_www_only" VALUES(9,1);
INSERT INTO "municipality_id_www_only" VALUES(10,0);
INSERT INTO "municipality_id_www_only" VALUES(11,0);
INSERT INTO "municipality_id_www_only" VALUES(12,0);
INSERT INTO "municipality_id_www_only" VALUES(13,0);
INSERT INTO "municipality_id_www_only" VALUES(14,0);
INSERT INTO "municipality_id_www_only" VALUES(15,0);
INSERT INTO "municipality_id_www_only" VALUES(16,0);
INSERT INTO "municipality_id_www_only" VALUES(17,0);
INSERT INTO "municipality_id_www_only" VALUES(18,0);
INSERT INTO "municipality_id_www_only" VALUES(19,0);
INSERT INTO "municipality_id_www_only" VALUES(20,0);
INSERT INTO "municipality_id_www_only" VALUES(21,0);
INSERT INTO "municipality_id_www_only" VALUES(22,0);
INSERT INTO "municipality_id_www_only" VALUES(23,0);
INSERT INTO "municipality_id_www_only" VALUES(24,0);
INSERT INTO "municipality_id_www_only" VALUES(25,0);
INSERT INTO "municipality_id_www_only" VALUES(26,0);
INSERT INTO "municipality_id_www_only" VALUES(27,0);
INSERT INTO "municipality_id_www_only" VALUES(28,0);
INSERT INTO "municipality_id_www_only" VALUES(29,0);
INSERT INTO "municipality_id_www_only" VALUES(30,0);
INSERT INTO "municipality_id_www_only" VALUES(31,0);
INSERT INTO "municipality_id_www_only" VALUES(32,0);
INSERT INTO "municipality_id_www_only" VALUES(33,1);
INSERT INTO "municipality_id_www_only" VALUES(34,0);
INSERT INTO "municipality_id_www_only" VALUES(35,0);
INSERT INTO "municipality_id_www_only" VALUES(36,0);
INSERT INTO "municipality_id_www_only" VALUES(37,1);
INSERT INTO "municipality_id_www_only" VALUES(38,1);
INSERT INTO "municipality_id_www_only" VALUES(39,0);
INSERT INTO "municipality_id_www_only" VALUES(40,0);
INSERT INTO "municipality_id_www_only" VALUES(41,0);
INSERT INTO "municipality_id_www_only" VALUES(42,0);
INSERT INTO "municipality_id_www_only" VALUES(43,0);
INSERT INTO "municipality_id_www_only" VALUES(44,0);
INSERT INTO "municipality_id_www_only" VALUES(45,0);
INSERT INTO "municipality_id_www_only" VALUES(46,0);
INSERT INTO "municipality_id_www_only" VALUES(47,0);
INSERT INTO "municipality_id_www_only" VALUES(48,0);
INSERT INTO "municipality_id_www_only" VALUES(49,0);
INSERT INTO "municipality_id_www_only" VALUES(50,0);
INSERT INTO "municipality_id_www_only" VALUES(51,0);
INSERT INTO "municipality_id_www_only" VALUES(52,0);
INSERT INTO "municipality_id_www_only" VALUES(53,1);
INSERT INTO "municipality_id_www_only" VALUES(54,0);
INSERT INTO "municipality_id_www_only" VALUES(55,0);
INSERT INTO "municipality_id_www_only" VALUES(56,0);
INSERT INTO "municipality_id_www_only" VALUES(57,1);
INSERT INTO "municipality_id_www_only" VALUES(58,0);
INSERT INTO "municipality_id_www_only" VALUES(59,0);
INSERT INTO "municipality_id_www_only" VALUES(60,1);
INSERT INTO "municipality_id_www_only" VALUES(61,0);
INSERT INTO "municipality_id_www_only" VALUES(62,0);
INSERT INTO "municipality_id_www_only" VALUES(63,0);
INSERT INTO "municipality_id_www_only" VALUES(64,0);
INSERT INTO "municipality_id_www_only" VALUES(65,0);
INSERT INTO "municipality_id_www_only" VALUES(66,0);
INSERT INTO "municipality_id_www_only" VALUES(67,0);
INSERT INTO "municipality_id_www_only" VALUES(68,0);
INSERT INTO "municipality_id_www_only" VALUES(69,0);
INSERT INTO "municipality_id_www_only" VALUES(70,0);
INSERT INTO "municipality_id_www_only" VALUES(71,0);
INSERT INTO "municipality_id_www_only" VALUES(72,0);
INSERT INTO "municipality_id_www_only" VALUES(73,0);
INSERT INTO "municipality_id_www_only" VALUES(74,0);
INSERT INTO "municipality_id_www_only" VALUES(75,1);
INSERT INTO "municipality_id_www_only" VALUES(76,0);
INSERT INTO "municipality_id_www_only" VALUES(77,0);
INSERT INTO "municipality_id_www_only" VALUES(78,0);
INSERT INTO "municipality_id_www_only" VALUES(79,0);
INSERT INTO "municipality_id_www_only" VALUES(80,0);
INSERT INTO "municipality_id_www_only" VALUES(81,0);
INSERT INTO "municipality_id_www_only" VALUES(82,0);
INSERT INTO "municipality_id_www_only" VALUES(83,0);
INSERT INTO "municipality_id_www_only" VALUES(84,0);
INSERT INTO "municipality_id_www_only" VALUES(85,0);
INSERT INTO "municipality_id_www_only" VALUES(86,0);
INSERT INTO "municipality_id_www_only" VALUES(87,0);
INSERT INTO "municipality_id_www_only" VALUES(88,0);
INSERT INTO "municipality_id_www_only" VALUES(89,0);
INSERT INTO "municipality_id_www_only" VALUES(90,0);
INSERT INTO "municipality_id_www_only" VALUES(91,0);
INSERT INTO "municipality_id_www_only" VALUES(92,0);
INSERT INTO "municipality_id_www_only" VALUES(93,0);
INSERT INTO "municipality_id_www_only" VALUES(94,0);
INSERT INTO "municipality_id_www_only" VALUES(95,0);
INSERT INTO "municipality_id_www_only" VALUES(96,0);
INSERT INTO "municipality_id_www_only" VALUES(97,0);
INSERT INTO "municipality_id_www_only" VALUES(98,0);
INSERT INTO "municipality_id_www_only" VALUES(99,0);
INSERT INTO "municipality_id_www_only" VALUES(100,0);
INSERT INTO "municipality_id_www_only" VALUES(101,0);
INSERT INTO "municipality_id_www_only" VALUES(102,0);
INSERT INTO "municipality_id_www_only" VALUES(103,0);
INSERT INTO "municipality_id_www_only" VALUES(104,0);
INSERT INTO "municipality_id_www_only" VALUES(105,0);
INSERT INTO "municipality_id_www_only" VALUES(106,0);
INSERT INTO "municipality_id_www_only" VALUES(107,0);
INSERT INTO "municipality_id_www_only" VALUES(108,0);
INSERT INTO "municipality_id_www_only" VALUES(109,0);
INSERT INTO "municipality_id_www_only" VALUES(110,0);
INSERT INTO "municipality_id_www_only" VALUES(111,0);
INSERT INTO "municipality_id_www_only" VALUES(112,0);
INSERT INTO "municipality_id_www_only" VALUES(113,0);
INSERT INTO "municipality_id_www_only" VALUES(114,1);
INSERT INTO "municipality_id_www_only" VALUES(115,0);
INSERT INTO "municipality_id_www_only" VALUES(116,0);
INSERT INTO "municipality_id_www_only" VALUES(117,0);
INSERT INTO "municipality_id_www_only" VALUES(118,0);
INSERT INTO "municipality_id_www_only" VALUES(119,0);
INSERT INTO "municipality_id_www_only" VALUES(120,0);
INSERT INTO "municipality_id_www_only" VALUES(121,0);
INSERT INTO "municipality_id_www_only" VALUES(122,0);
INSERT INTO "municipality_id_www_only" VALUES(123,0);
INSERT INTO "municipality_id_www_only" VALUES(124,0);
INSERT INTO "municipality_id_www_only" VALUES(125,0);
INSERT INTO "municipality_id_www_only" VALUES(126,0);
INSERT INTO "municipality_id_www_only" VALUES(127,0);
INSERT INTO "municipality_id_www_only" VALUES(128,0);
INSERT INTO "municipality_id_www_only" VALUES(129,0);
INSERT INTO "municipality_id_www_only" VALUES(130,0);
INSERT INTO "municipality_id_www_only" VALUES(131,0);
INSERT INTO "municipality_id_www_only" VALUES(132,0);
INSERT INTO "municipality_id_www_only" VALUES(133,1);
INSERT INTO "municipality_id_www_only" VALUES(134,0);
INSERT INTO "municipality_id_www_only" VALUES(135,0);
INSERT INTO "municipality_id_www_only" VALUES(136,0);
INSERT INTO "municipality_id_www_only" VALUES(137,0);
INSERT INTO "municipality_id_www_only" VALUES(138,0);
INSERT INTO "municipality_id_www_only" VALUES(139,0);
INSERT INTO "municipality_id_www_only" VALUES(140,0);
INSERT INTO "municipality_id_www_only" VALUES(141,0);
INSERT INTO "municipality_id_www_only" VALUES(142,0);
INSERT INTO "municipality_id_www_only" VALUES(143,0);
INSERT INTO "municipality_id_www_only" VALUES(144,0);
INSERT INTO "municipality_id_www_only" VALUES(145,0);
INSERT INTO "municipality_id_www_only" VALUES(146,0);
INSERT INTO "municipality_id_www_only" VALUES(147,1);
INSERT INTO "municipality_id_www_only" VALUES(148,0);
INSERT INTO "municipality_id_www_only" VALUES(149,0);
INSERT INTO "municipality_id_www_only" VALUES(150,0);
INSERT INTO "municipality_id_www_only" VALUES(151,0);
INSERT INTO "municipality_id_www_only" VALUES(152,0);
INSERT INTO "municipality_id_www_only" VALUES(153,0);
INSERT INTO "municipality_id_www_only" VALUES(154,0);
INSERT INTO "municipality_id_www_only" VALUES(155,0);
INSERT INTO "municipality_id_www_only" VALUES(156,0);
INSERT INTO "municipality_id_www_only" VALUES(157,0);
INSERT INTO "municipality_id_www_only" VALUES(158,0);
INSERT INTO "municipality_id_www_only" VALUES(159,0);
INSERT INTO "municipality_id_www_only" VALUES(160,0);
INSERT INTO "municipality_id_www_only" VALUES(161,0);
INSERT INTO "municipality_id_www_only" VALUES(162,0);
INSERT INTO "municipality_id_www_only" VALUES(163,0);
INSERT INTO "municipality_id_www_only" VALUES(164,1);
INSERT INTO "municipality_id_www_only" VALUES(165,0);
INSERT INTO "municipality_id_www_only" VALUES(166,0);
INSERT INTO "municipality_id_www_only" VALUES(167,0);
INSERT INTO "municipality_id_www_only" VALUES(168,1);
INSERT INTO "municipality_id_www_only" VALUES(169,0);
INSERT INTO "municipality_id_www_only" VALUES(170,0);
INSERT INTO "municipality_id_www_only" VALUES(171,0);
INSERT INTO "municipality_id_www_only" VALUES(172,0);
INSERT INTO "municipality_id_www_only" VALUES(173,0);
INSERT INTO "municipality_id_www_only" VALUES(174,0);
INSERT INTO "municipality_id_www_only" VALUES(175,0);
INSERT INTO "municipality_id_www_only" VALUES(176,0);
INSERT INTO "municipality_id_www_only" VALUES(177,1);
INSERT INTO "municipality_id_www_only" VALUES(178,0);
INSERT INTO "municipality_id_www_only" VALUES(179,0);
INSERT INTO "municipality_id_www_only" VALUES(180,0);
INSERT INTO "municipality_id_www_only" VALUES(181,0);
INSERT INTO "municipality_id_www_only" VALUES(182,0);
INSERT INTO "municipality_id_www_only" VALUES(183,0);
INSERT INTO "municipality_id_www_only" VALUES(184,0);
INSERT INTO "municipality_id_www_only" VALUES(185,0);
INSERT INTO "municipality_id_www_only" VALUES(186,0);
INSERT INTO "municipality_id_www_only" VALUES(187,0);
INSERT INTO "municipality_id_www_only" VALUES(188,0);
INSERT INTO "municipality_id_www_only" VALUES(189,0);
INSERT INTO "municipality_id_www_only" VALUES(190,0);
INSERT INTO "municipality_id_www_only" VALUES(191,1);
INSERT INTO "municipality_id_www_only" VALUES(192,0);
INSERT INTO "municipality_id_www_only" VALUES(193,0);
INSERT INTO "municipality_id_www_only" VALUES(194,0);
INSERT INTO "municipality_id_www_only" VALUES(195,0);
INSERT INTO "municipality_id_www_only" VALUES(196,0);
INSERT INTO "municipality_id_www_only" VALUES(197,0);
INSERT INTO "municipality_id_www_only" VALUES(198,0);
INSERT INTO "municipality_id_www_only" VALUES(199,0);
INSERT INTO "municipality_id_www_only" VALUES(200,0);
INSERT INTO "municipality_id_www_only" VALUES(201,1);
INSERT INTO "municipality_id_www_only" VALUES(202,0);
INSERT INTO "municipality_id_www_only" VALUES(203,0);
INSERT INTO "municipality_id_www_only" VALUES(204,0);
INSERT INTO "municipality_id_www_only" VALUES(205,0);
INSERT INTO "municipality_id_www_only" VALUES(206,0);
INSERT INTO "municipality_id_www_only" VALUES(207,0);
INSERT INTO "municipality_id_www_only" VALUES(208,0);
INSERT INTO "municipality_id_www_only" VALUES(209,0);
INSERT INTO "municipality_id_www_only" VALUES(210,0);
INSERT INTO "municipality_id_www_only" VALUES(211,1);
INSERT INTO "municipality_id_www_only" VALUES(212,0);
INSERT INTO "municipality_id_www_only" VALUES(213,0);
INSERT INTO "municipality_id_www_only" VALUES(214,1);
INSERT INTO "municipality_id_www_only" VALUES(215,0);
INSERT INTO "municipality_id_www_only" VALUES(216,0);
INSERT INTO "municipality_id_www_only" VALUES(217,0);
INSERT INTO "municipality_id_www_only" VALUES(218,0);
INSERT INTO "municipality_id_www_only" VALUES(219,0);
INSERT INTO "municipality_id_www_only" VALUES(220,0);
INSERT INTO "municipality_id_www_only" VALUES(221,0);
INSERT INTO "municipality_id_www_only" VALUES(222,0);
INSERT INTO "municipality_id_www_only" VALUES(223,1);
INSERT INTO "municipality_id_www_only" VALUES(224,1);
INSERT INTO "municipality_id_www_only" VALUES(225,0);
INSERT INTO "municipality_id_www_only" VALUES(226,0);
INSERT INTO "municipality_id_www_only" VALUES(227,0);
INSERT INTO "municipality_id_www_only" VALUES(228,0);
INSERT INTO "municipality_id_www_only" VALUES(229,0);
INSERT INTO "municipality_id_www_only" VALUES(230,1);
INSERT INTO "municipality_id_www_only" VALUES(231,0);
INSERT INTO "municipality_id_www_only" VALUES(232,0);
INSERT INTO "municipality_id_www_only" VALUES(233,0);
INSERT INTO "municipality_id_www_only" VALUES(234,0);
INSERT INTO "municipality_id_www_only" VALUES(235,0);
INSERT INTO "municipality_id_www_only" VALUES(236,0);
INSERT INTO "municipality_id_www_only" VALUES(237,0);
INSERT INTO "municipality_id_www_only" VALUES(238,0);
INSERT INTO "municipality_id_www_only" VALUES(239,0);
INSERT INTO "municipality_id_www_only" VALUES(240,1);
INSERT INTO "municipality_id_www_only" VALUES(241,0);
INSERT INTO "municipality_id_www_only" VALUES(242,0);
INSERT INTO "municipality_id_www_only" VALUES(243,0);
INSERT INTO "municipality_id_www_only" VALUES(244,0);
INSERT INTO "municipality_id_www_only" VALUES(245,0);
INSERT INTO "municipality_id_www_only" VALUES(246,0);
INSERT INTO "municipality_id_www_only" VALUES(247,0);
INSERT INTO "municipality_id_www_only" VALUES(248,1);
INSERT INTO "municipality_id_www_only" VALUES(249,0);
INSERT INTO "municipality_id_www_only" VALUES(250,1);
INSERT INTO "municipality_id_www_only" VALUES(251,0);
INSERT INTO "municipality_id_www_only" VALUES(252,0);
INSERT INTO "municipality_id_www_only" VALUES(253,0);
INSERT INTO "municipality_id_www_only" VALUES(254,0);
INSERT INTO "municipality_id_www_only" VALUES(255,0);
INSERT INTO "municipality_id_www_only" VALUES(256,0);
INSERT INTO "municipality_id_www_only" VALUES(257,1);
INSERT INTO "municipality_id_www_only" VALUES(258,1);
INSERT INTO "municipality_id_www_only" VALUES(259,0);
INSERT INTO "municipality_id_www_only" VALUES(260,0);
INSERT INTO "municipality_id_www_only" VALUES(261,0);
INSERT INTO "municipality_id_www_only" VALUES(262,0);
INSERT INTO "municipality_id_www_only" VALUES(263,0);
INSERT INTO "municipality_id_www_only" VALUES(264,0);
INSERT INTO "municipality_id_www_only" VALUES(265,0);
INSERT INTO "municipality_id_www_only" VALUES(266,0);
INSERT INTO "municipality_id_www_only" VALUES(267,0);
INSERT INTO "municipality_id_www_only" VALUES(268,0);
INSERT INTO "municipality_id_www_only" VALUES(269,0);
INSERT INTO "municipality_id_www_only" VALUES(270,0);
INSERT INTO "municipality_id_www_only" VALUES(271,0);
INSERT INTO "municipality_id_www_only" VALUES(272,0);
INSERT INTO "municipality_id_www_only" VALUES(273,0);
INSERT INTO "municipality_id_www_only" VALUES(274,0);
INSERT INTO "municipality_id_www_only" VALUES(275,0);
INSERT INTO "municipality_id_www_only" VALUES(276,0);
INSERT INTO "municipality_id_www_only" VALUES(277,0);
INSERT INTO "municipality_id_www_only" VALUES(278,0);
INSERT INTO "municipality_id_www_only" VALUES(279,0);
INSERT INTO "municipality_id_www_only" VALUES(280,1);
INSERT INTO "municipality_id_www_only" VALUES(281,0);
INSERT INTO "municipality_id_www_only" VALUES(282,0);
INSERT INTO "municipality_id_www_only" VALUES(283,0);
INSERT INTO "municipality_id_www_only" VALUES(284,0);
INSERT INTO "municipality_id_www_only" VALUES(285,0);
INSERT INTO "municipality_id_www_only" VALUES(286,0);
INSERT INTO "municipality_id_www_only" VALUES(287,0);
INSERT INTO "municipality_id_www_only" VALUES(288,0);
INSERT INTO "municipality_id_www_only" VALUES(289,0);
INSERT INTO "municipality_id_www_only" VALUES(290,1);
COMMIT;
